apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsdb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-products
  template:
    metadata:
      labels:
        app: postgres-products
    spec:
      containers:
        - name: postgres-products
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: productdb-srv
spec:
  type: NodePort
  selector:
    app: postgres-products
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
