# Generated by Django 5.0.1 on 2024-01-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
    ]
